export function makePool() {
  let id = 1;
  const q = [];
  const addSingle = (topic, stem, choices, answer, explanation, exhibit = '', difficulty = 'CCNA-hard') => q.push({ id: id++, type: 'single', topic, stem, choices, answer, explanation, exhibit, difficulty });
  const addMulti = (topic, stem, choices, answer, explanation, exhibit = '', difficulty = 'CCNA-hard') => q.push({ id: id++, type: 'multi', topic, stem, choices, answer, explanation, exhibit, difficulty });
  const addCommand = (topic, stem, answers, explanation, hint = '', exhibit = '', difficulty = 'CCNA-hard') => q.push({ id: id++, type: 'command', topic, stem, answers, explanation, hint, exhibit, difficulty });
  const addMatch = (topic, stem, prompts, options, answerMap, explanation, exhibit = '', difficulty = 'CCNA-hard') => q.push({ id: id++, type: 'match', topic, stem, prompts, options, answerMap, explanation, exhibit, difficulty });

  const concept = [
    ['STP purpose','A three-switch Layer 2 triangle is built with all links forwarding and no STP. Which failure symptom is STP primarily designed to prevent?',['Routing black holes caused by missing default routes','Layer 2 loops causing broadcast replication, MAC instability, and duplicate frames','IP address conflicts between hosts in the same subnet','Native VLAN mismatch on a trunk'],1,'STP prevents Layer 2 loops by intentionally blocking redundant paths while keeping redundancy available.'],
    ['Bridge ID','With extended system ID enabled, which value is actually compared first when electing the root bridge for VLAN 30?',['The configured base priority only','The configured base priority plus VLAN ID, then MAC address','The lowest interface MAC address on any trunk','The lowest root path cost advertised by neighbors'],1,'Cisco PVST+/Rapid PVST+ uses a per-VLAN bridge ID: priority + extended system ID + MAC address.'],
    ['Root election','All switches have default STP priority in VLAN 10. Which switch becomes root?',['The switch with the most trunks','The switch with the lowest MAC address','The switch with the lowest root path cost','The switch with the highest MAC address'],1,'If priority ties, the lowest MAC address wins the root election.'],
    ['PVST+','What is the operational consequence of PVST+ or Rapid PVST+ compared with a single common STP instance?',['Only VLAN 1 participates in STP','Each VLAN can elect a different root bridge and produce a different forwarding topology','STP is disabled on access ports by default','All VLANs must share the same blocked physical port'],1,'PVST+/Rapid PVST+ creates a separate STP instance per VLAN, enabling per-VLAN root placement and load balancing.'],
    ['Root bridge','In a normal STP topology, what is true about ports on the root bridge?',['They are all root ports','They are all alternate ports','They are designated ports, unless there is an unusual loopback/shared-segment exception','They are blocked until receiving superior BPDUs'],2,'The root bridge has no root port. Its ports are designated for their segments in normal designs.'],
    ['Root port selection','A non-root switch receives equal-cost BPDUs to the same root from two neighbors. Which tie-breaker is evaluated before sender port ID?',['Lowest local port number','Lowest sender bridge ID','Lowest VLAN number','Highest interface bandwidth'],1,'Root port selection: lowest root path cost, then lowest sender bridge ID, then lowest sender port ID, then lowest local port ID.'],
    ['Designated port','On a segment between two non-root switches, how is the designated port selected?',['The port on the switch with the lowest path cost to the root wins','The port with the highest MAC address wins','The port closest to an end host wins','The port with PortFast enabled wins'],0,'For each segment, the switch advertising the best BPDU toward the root has the designated port.'],
    ['Classic STP states','Which 802.1D STP state learns MAC addresses but still does not forward user frames?',['Blocking','Listening','Learning','Forwarding'],2,'Learning builds the MAC table but does not forward data frames yet.'],
    ['Rapid STP states','Which set correctly represents Rapid STP port states?',['Blocking, listening, learning, forwarding','Discarding, learning, forwarding','Blocking, learning, forwarding, err-disabled','Listening, learning, forwarding, disabled'],1,'RSTP compresses blocking/listening/disabled behavior into discarding, then learning, then forwarding.'],
    ['Rapid STP roles','Which RSTP role represents a backup path to the root bridge and is normally discarding?',['Root','Designated','Alternate','Edge'],2,'An alternate port provides an alternate path to the root and remains discarding/blocking until needed.'],
    ['Backup port','A switch has two ports connected to the same shared segment/hub and one of its own ports already wins as designated. What is the role of the other local port?',['Root port','Alternate port','Backup port','Boundary port'],2,'Backup is a redundant local port to the same segment, not an alternate path through a different bridge.'],
    ['PortFast','Which statement is the safest interpretation of PortFast on an access port?',['It disables all BPDU processing permanently','It allows the port to skip listening/learning and move quickly to forwarding for end-host connectivity','It makes the switch root for that VLAN','It increases the STP path cost to prevent loops'],1,'PortFast is for edge/end-host ports so hosts do not wait for normal STP convergence.'],
    ['PortFast risk','Why is PortFast dangerous on a port connected to another switch?',['It changes the native VLAN','It may put a looped link into forwarding before STP can protect the topology','It disables trunk negotiation','It lowers the bridge priority to zero'],1,'PortFast assumes no Layer 2 loop exists. Use it on host-facing ports, usually with BPDU Guard.'],
    ['BPDU Guard','A PortFast access interface receives a BPDU and BPDU Guard is enabled. What should happen?',['The interface becomes root-inconsistent','The interface becomes loop-inconsistent','The interface is placed into err-disabled state','The interface silently filters future BPDUs but keeps forwarding'],2,'BPDU Guard protects edge ports by err-disabling the port when it receives a BPDU.'],
    ['Root Guard','A designated access-layer uplink receives a superior BPDU from an unexpected switch while Root Guard is enabled. What state is expected?',['Err-disabled','Root-inconsistent','Loop-inconsistent','Forwarding as root port'],1,'Root Guard prevents the port from becoming a root port and places it into root-inconsistent until superior BPDUs stop.'],
    ['Loop Guard','Loop Guard is mainly designed to protect against which condition?',['A superior BPDU arriving on an edge port','A root/alternate port losing expected BPDUs and incorrectly moving toward forwarding','A native VLAN mismatch','A switch with a lower bridge priority joining the LAN'],1,'Loop Guard keeps a port from moving to forwarding when expected BPDUs disappear, reducing unidirectional-link loop risk.'],
    ['BPDU Filter','Which BPDU Filter deployment is most dangerous if used blindly on a switch-to-switch port?',['Per-interface BPDU Filter enable','Global PortFast BPDU Filter default','BPDU Guard default','Root Guard'],0,'Per-interface BPDU Filter can stop sending and receiving BPDUs on that port, potentially hiding a loop from STP.'],
    ['Port roles','In Rapid PVST+, which two port roles normally forward user traffic after convergence?',['Root and designated','Alternate and backup','Root and alternate','Backup and designated only'],0,'Root and designated ports forward. Alternate/backup are discarding unless reconvergence changes roles.'],
    ['STP costs','Using classic short path cost, which interface normally has the lowest STP cost?',['10 Mbps Ethernet','100 Mbps FastEthernet','1 Gbps GigabitEthernet','All speeds use cost 19'],2,'Classic short cost: 10 Mbps = 100, 100 Mbps = 19, 1 Gbps = 4, 10 Gbps = 2.'],
    ['Tie-breakers','Two parallel links connect SW2 to the root switch. Both have equal path cost and receive BPDUs from the same neighbor bridge. What typically breaks the final tie?',['Lowest local port ID','Highest local port ID','Lowest VLAN ID','Lowest root bridge MAC'],0,'When received BPDUs are otherwise identical, the lowest local port ID becomes the root port.'],
    ['Rapid convergence','Which Rapid STP mechanism allows a point-to-point designated port to move rapidly to forwarding after synchronization?',['Max-age expiration','Proposal/agreement','DNS lookup','Route poisoning'],1,'RSTP uses proposal/agreement on point-to-point links for rapid transition.'],
    ['RSTP edge','What happens to an RSTP edge port if it receives a BPDU, assuming no BPDU Guard is configured?',['It should lose edge behavior and participate as a normal STP port','It remains permanently edge and ignores the BPDU','It becomes root-inconsistent','It disables STP for the VLAN'],0,'An edge port receiving BPDUs is no longer behaving like a pure host-facing edge.'],
    ['Topology changes','In STP, which event is most likely to trigger a topology change process?',['A port participating in STP moves to forwarding or from forwarding','A host sends an ARP request','A router changes its OSPF metric','A switch reloads its startup-config'],0,'STP topology changes are tied to forwarding-state transitions, not ordinary host traffic.'],
    ['STP and trunks','On a trunk carrying VLANs 10 and 20 under Rapid PVST+, what is true?',['The same physical interface can have different STP roles per VLAN','Only VLAN 1 can block','Trunks cannot participate in Rapid PVST+','All VLANs must use the native VLAN root'],0,'Because Rapid PVST+ runs per VLAN, the same trunk can forward for one VLAN and block for another.'],
    ['Bridge priority','Which manually configured bridge priority is valid with extended system ID?',['32767','4097','24576','50000'],2,'Bridge priority values are configured in increments of 4096.'],
    ['Port priority','Which configured STP port priority is valid on Cisco IOS?',['10','64','130','255'],1,'Port priority uses increments of 16; default is 128. 64 is valid.'],
    ['Root primary','What does `spanning-tree vlan 10 root primary` try to accomplish?',['It disables STP on VLAN 10','It sets the switch priority low enough to become root if possible','It makes every port a root port','It forces all trunks to block VLAN 10'],1,'The macro adjusts priority to influence root election; it does not guarantee success against an even lower configured priority.'],
    ['Root secondary','What is the goal of `spanning-tree vlan 10 root secondary`?',['Make the switch a backup candidate root if the primary root fails','Make the switch block all access ports','Enable Rapid PVST+ globally','Turn all non-root ports into PortFast'],0,'Root secondary usually sets priority to 28672 so it is preferred over default switches but below the primary.'],
    ['Show output','In `show spanning-tree`, what does `Root ID ... This bridge is the root` mean?',['The local switch is root for the displayed VLAN/instance','The local switch has a root port','The displayed interface is blocked','The local switch is not participating in STP'],0,'That line means the local bridge is the root for that STP instance.'],
    ['Show output','In Cisco `show spanning-tree`, what does `Altn BLK` most directly indicate?',['Forwarding designated port','Blocked alternate path','Root port forwarding','PortFast edge forwarding'],1,'Altn BLK means alternate role in blocking/discarding state.'],
    ['Show output','Which `show spanning-tree` value is most directly used to identify the root bridge selected for a VLAN?',['Bridge ID','Root ID','Interface Type','Hello Time only'],1,'Root ID describes the elected root. Bridge ID describes the local switch.'],
    ['EtherChannel','How does STP normally treat a Layer 2 EtherChannel?',['As one logical port-channel interface','As separate physical links that can independently block','As a router interface only','As a PortFast-only link'],0,'STP sees the port-channel as the logical STP port, which prevents one member from blocking independently.'],
    ['Protection feature choice','You want to make sure an access-layer switch can never become root through a port connected toward a downstream unmanaged switch. Which feature best fits?',['Root Guard on the designated/downstream-facing port','Loop Guard on the host port','BPDU Filter on all trunks','Lower the access switch MAC address'],0,'Root Guard enforces root placement by blocking superior BPDUs on ports that should remain designated.'],
    ['Protection feature choice','You want host-facing ports to shut if someone plugs in a switch. Which feature best fits?',['Root Guard','BPDU Guard','Loop Guard','UplinkFast'],1,'BPDU Guard is the standard protection on PortFast/edge ports.'],
    ['Protection feature choice','A fiber link may become unidirectional, causing a blocked port to stop receiving BPDUs. Which feature is most relevant?',['Loop Guard','BPDU Guard','PortFast','Root primary'],0,'Loop Guard protects against loss of BPDUs on root/alternate ports.'],
    ['Mode','Which command mode change is required before using Rapid PVST+ behavior globally?',['`spanning-tree mode rapid-pvst`','`spanning-tree vlan all root rapid`','`rapid-pvst enable`','`stp mode 802.1w`'],0,'The IOS global command is `spanning-tree mode rapid-pvst`.'],
    ['STP operation','Which item is carried inside a configuration BPDU and directly affects STP decisions?',['Root bridge ID','IP default gateway','ARP table age','OSPF router ID'],0,'BPDUs include root ID, path cost, sender bridge ID, sender port ID, and timers.'],
    ['PortFast trunk','When might `spanning-tree portfast trunk` be appropriate?',['On a trunk to another access switch','On a trunk to a router-on-a-stick or server/virtualization host where no Layer 2 loop can exist','On every distribution trunk','Never; the command does not exist'],1,'PortFast trunk can be used for edge trunk scenarios, not for switch-to-switch redundant trunks.'],
    ['Default behavior','On many Cisco Catalyst switches, what is the traditional default STP mode?',['PVST+','MST only','Rapid PVST+ only','STP disabled'],0,'Traditional Catalyst behavior is PVST+ by default, although modern labs may explicitly configure Rapid PVST+.'],
    ['Load balancing','Which design best uses PVST+/Rapid PVST+ for Layer 2 load sharing?',['Make SW1 root for all VLANs and block every backup uplink','Make SW1 root for VLAN 10 and SW2 root for VLAN 20, matching HSRP/VRRP gateways if present','Disable STP on VLAN 20','Use PortFast on inter-switch trunks'],1,'Per-VLAN root placement can align traffic paths with gateway placement.'],
    ['Timers','In classic 802.1D STP defaults, approximately how long can a port take to move from blocking/listening toward forwarding after normal convergence?',['1 second','2 seconds','About 30 seconds through listening and learning','5 minutes'],2,'Classic STP commonly waits 15 seconds in listening and 15 seconds in learning.'],
    ['RSTP vs STP','Which legacy STP features are effectively built into RSTP behavior rather than configured separately for normal use?',['UplinkFast and BackboneFast','NAT and PAT','HSRP and VRRP','LACP and PAgP'],0,'RSTP includes faster convergence behavior that replaced those old acceleration features.'],
    ['RSTP compatibility','A Rapid PVST+ switch receives legacy 802.1D BPDUs on a port. What is the expected high-level behavior?',['It can fall back to 802.1D behavior on that port','It immediately disables VLAN 1','It converts the neighbor to RSTP automatically','It ignores all legacy BPDUs'],0,'RSTP is backward-compatible and can interoperate with legacy STP on a port.'],
    ['Root path cost','A switch has a direct 100-Mb link to the root and an indirect path through two 1-Gb links. With short path cost, which path is preferred?',['Direct 100-Mb path cost 19','Indirect 1-Gb + 1-Gb path cost 8','Both tie','The path with the higher neighbor MAC'],1,'STP sums path cost to the root. Two Gigabit links cost 8, which beats FastEthernet cost 19.'],
    ['Blocked traffic','A port in blocking/discarding state still normally processes which control traffic?',['STP BPDUs','User data frames','Routed IP packets','DHCP offers only'],0,'Blocked/discarding STP ports do not forward user frames, but they still receive/process BPDUs.']
  ];
  concept.forEach(c => addSingle(...c));

  const electionSets = [
    { vlan: 10, sw: [['SW1', 32768, '0000.1111.1111'], ['SW2', 32768, '0000.2222.2222'], ['SW3', 28672, '0000.3333.3333']] },
    { vlan: 20, sw: [['DSW1', 24576, '00aa.0000.1000'], ['DSW2', 24576, '00aa.0000.000f'], ['ASW1', 32768, '0001.0000.0001']] },
    { vlan: 99, sw: [['CORE-A', 4096, '0050.aaaa.0001'], ['CORE-B', 8192, '0001.bbbb.0001'], ['ACC-1', 4096, '0050.aaaa.0000']] },
    { vlan: 30, sw: [['S1', 32768, '00d0.0000.0003'], ['S2', 32768, '00d0.0000.0002'], ['S3', 32768, '00d0.0000.0001']] },
    { vlan: 40, sw: [['A', 28672, '0c11.aaaa.1000'], ['B', 24576, '0c11.ffff.0001'], ['C', 24576, '0c11.0000.ffff']] },
    { vlan: 50, sw: [['SW-A', 8192, 'aaaa.0000.0100'], ['SW-B', 4096, 'bbbb.0000.0100'], ['SW-C', 4096, 'aaaa.0000.0200']] },
    { vlan: 60, sw: [['X1', 32768, '000a.aaaa.aaaa'], ['X2', 28672, '000b.bbbb.bbbb'], ['X3', 24576, '000c.cccc.cccc']] },
    { vlan: 70, sw: [['R1', 12288, '00aa.1111.1111'], ['R2', 12288, '00aa.1111.1110'], ['R3', 16384, '0000.0000.0001']] },
    { vlan: 80, sw: [['MDF', 20480, '1111.1111.1111'], ['IDF1', 20480, '1111.1111.1112'], ['IDF2', 20480, '1111.1111.1110']] },
    { vlan: 200, sw: [['BLUE', 28672, 'abcd.0000.0001'], ['RED', 28672, 'abcd.0000.0002'], ['GREEN', 24576, 'ffff.0000.0001']] },
  ];
  const bridgeId = (sw, vlan) => sw[1] + vlan;
  const macValue = mac => mac.replace(/\./g, '');
  electionSets.forEach((set) => {
    const exhibit = `VLAN ${set.vlan}\n${set.sw.map(s => `${s[0]} priority ${s[1]} MAC ${s[2]} bridge-id-priority ${bridgeId(s, set.vlan)}`).join('\n')}`;
    const sorted = [...set.sw].sort((a, b) => bridgeId(a, set.vlan) - bridgeId(b, set.vlan) || macValue(a[2]).localeCompare(macValue(b[2])));
    const names = set.sw.map(s => s[0]);
    addSingle('Root election', `Which switch becomes the root bridge for VLAN ${set.vlan}?`, names, names.indexOf(sorted[0][0]), `Lowest bridge ID wins: priority plus VLAN ID first, then MAC address. ${sorted[0][0]} has the lowest resulting bridge ID.`, exhibit);
    addSingle('Bridge ID', `Which comparison decides the winner if two switches in VLAN ${set.vlan} have the same configured priority?`, ['Lowest MAC address','Highest MAC address','Lowest local port ID','Lowest root path cost'], 0, 'For root bridge election, if bridge priority ties, the lowest MAC address wins.', exhibit);
    addSingle('Root election', `A new switch joins VLAN ${set.vlan} with priority ${sorted[0][1]} and MAC 0000.0000.0001. What happens if that priority ties the current root?`, ['The new switch becomes root because its MAC is lower','The current root remains root because it was first','The switch with the highest port count wins','No election happens until a reload'], 0, 'STP is deterministic; if priority ties, lower MAC wins, even if the switch joined later.', exhibit);
  });

  const topoScenarios = [
    { exhibit: 'SW1 is root for VLAN 10.\nLinks: SW1--SW2 Gigabit cost 4, SW1--SW3 FastEthernet cost 19, SW2--SW3 Gigabit cost 4.', qs: [
      ['On SW3, which port becomes the root port?', ['Toward SW1','Toward SW2','Both forward as root ports','Neither; SW3 is root'], 1, 'SW3 reaches the root through SW2 with cost 8, better than direct FastEthernet cost 19.'],
      ['On the SW1--SW3 segment, what is SW3\'s port role/state?', ['Root forwarding','Designated forwarding','Alternate blocking/discarding','Backup forwarding'], 2, 'SW1 is root and designated on the segment; SW3\'s direct path is worse than its path through SW2.'],
      ['On the SW2--SW3 segment, which switch has the designated port?', ['SW2','SW3','Both','Neither'], 0, 'SW2 has lower root path cost to SW1 (4) than SW3 (8).'] ]},
    { exhibit: 'SW-A is root for VLAN 20.\nLinks: SW-A--SW-B FastEthernet cost 19, SW-A--SW-C FastEthernet cost 19, SW-B--SW-C Gigabit cost 4.\nSW-B BID is lower than SW-C BID.', qs: [
      ['Which port is SW-C\'s root port?', ['Toward SW-A','Toward SW-B','Both tie and forward','The lower local port ID automatically'], 0, 'Direct cost to root is 19. Through SW-B is 23, so direct wins.'],
      ['On SW-B--SW-C, which side is designated?', ['SW-B','SW-C','Both alternate','Root bridge side'], 0, 'Both have equal root path cost 19, so lower bridge ID wins. SW-B is lower.'],
      ['Which port is likely blocked?', ['SW-C toward SW-B','SW-C toward SW-A','SW-B toward SW-A','SW-A toward SW-B'], 0, 'SW-C loses designated election on the SW-B--SW-C segment and already has root port toward SW-A.'] ]},
    { exhibit: 'Same physical triangle: DSW1--ASW1, DSW2--ASW1, DSW1--DSW2 all Gigabit.\nDSW1 is root for VLAN 10. DSW2 is root for VLAN 20.', qs: [
      ['What can be true on ASW1\'s uplinks?', ['One physical uplink can be root port for VLAN 10 and the other for VLAN 20','Both VLANs must block the same uplink','ASW1 must be root for both VLANs','Rapid PVST+ disables VLAN 20'], 0, 'Per-VLAN STP permits different logical topologies on the same physical links.'],
      ['For VLAN 10, which uplink is ASW1 most likely to use as root port if costs are equal?', ['Toward DSW1','Toward DSW2','Toward itself','No root port exists on non-root switch'], 0, 'The root port is the best path to the VLAN root, DSW1.'],
      ['For VLAN 20, which uplink is ASW1 most likely to use as root port if costs are equal?', ['Toward DSW1','Toward DSW2','Both blocked','No STP on trunks'], 1, 'VLAN 20 root is DSW2, so ASW1 best path normally points to DSW2.'] ]},
    { exhibit: 'SW2 has two equal-speed links to root SW1: Gi0/1 and Gi0/2.\nBoth receive identical superior BPDUs from SW1.\nAssume sender bridge ID and sender port ID tie.', qs: [
      ['Which local port is preferred as SW2\'s root port?', ['Gi0/1','Gi0/2','Both become root ports','The port with higher local number'], 0, 'With all received BPDU fields tied, the lower local port ID wins.'],
      ['What happens to the other parallel port?', ['It is normally alternate/discarding','It becomes designated forwarding','It becomes disabled administratively','It becomes a routed port'], 0, 'One equal parallel link is used; the redundant link blocks/discards to prevent a loop.'],
      ['Which design avoids one physical member blocking independently in a bundled uplink?', ['Layer 2 EtherChannel','BPDU Filter','Disabling STP','Root Guard on both ends'], 0, 'STP treats a port-channel as one logical link.'] ]},
    { exhibit: 'Core1 is intended root. AccessSW is connected downstream to Core1. A user connects a cheap switch with priority 0 to AccessSW Fa0/10.', qs: [
      ['Without protection, what is the STP risk?', ['The cheap switch may become root if its bridge ID is superior','The VLAN native ID changes automatically','Core1 ignores all BPDUs','All access ports become routed ports'], 0, 'A superior BPDU from an unexpected switch can win root election if not controlled.'],
      ['Which feature on Fa0/10 best shuts the port if a switch is connected?', ['BPDU Guard','Loop Guard','Root secondary','UplinkFast'], 0, 'Host-facing PortFast ports should usually use BPDU Guard.'],
      ['If the port is not host-facing but should never lead to the root, which feature is better?', ['Root Guard','BPDU Filter','PortFast trunk everywhere','Disable CDP'], 0, 'Root Guard is used on ports that should remain designated and never become root ports.'] ]},
    { exhibit: 'SW2 has an alternate port blocking toward SW3. Because of a fiber fault, SW2 stops receiving BPDUs on that port, but the physical link remains up.', qs: [
      ['Which feature is designed for this failure pattern?', ['Loop Guard','BPDU Guard','PortFast','Root primary'], 0, 'Loop Guard prevents a blocked/root/alternate port from becoming forwarding because BPDUs stopped arriving.'],
      ['What state can Loop Guard place the port into?', ['Loop-inconsistent','Root-inconsistent','Err-disabled','Administratively down'], 0, 'Loop Guard uses loop-inconsistent state and recovers automatically when BPDUs return.'],
      ['Why is BPDU Guard not the best fit here?', ['BPDU Guard reacts to receiving BPDUs on an edge port, not to missing BPDUs on a redundant link','BPDU Guard only works on routers','BPDU Guard elects the root','BPDU Guard only changes VLAN names'], 0, 'BPDU Guard protects edge ports from unexpected BPDUs.'] ]},
    { exhibit: 'Root is SW1. SW2 and SW3 connect on a shared VLAN segment.\nSW2 root path cost = 8. SW3 root path cost = 12.', qs: [
      ['Which switch is designated on the SW2-SW3 segment?', ['SW2','SW3','Both','Root only'], 0, 'Lower advertised cost to root wins the designated port role on the segment.'],
      ['What role is SW3\'s port on that segment if it already has another root port?', ['Alternate','Root','Designated','Edge'], 0, 'SW3 loses the segment election and keeps the port as an alternate path.'],
      ['If both costs changed to 8, what is the next tie-breaker?', ['Lowest bridge ID','Highest interface speed','Highest VLAN ID','Lowest native VLAN'], 0, 'Designated port tie-breaker after cost is lowest bridge ID.'] ]},
    { exhibit: 'SW4 is not root. It has two possible paths to the root.\nVia SW2: root path cost 12, sender BID 32778:aaaa.aaaa.aaaa, sender port ID 128.1\nVia SW3: root path cost 12, sender BID 32778:bbbb.bbbb.bbbb, sender port ID 128.1', qs: [
      ['Which neighbor is selected for SW4\'s root port?', ['SW2','SW3','Both','Neither'], 0, 'Costs tie, sender BID decides; aaaa is lower than bbbb.'],
      ['Which field did NOT need to be evaluated?', ['Sender port ID','Root path cost','Sender bridge ID','Root ID'], 0, 'The tie is broken at sender BID, so sender port ID is not needed.'],
      ['If sender BIDs also tied, what would be compared next?', ['Sender port ID','Local VLAN name','MAC table size','DHCP lease time'], 0, 'Root port selection continues to sender port ID, then local port ID.'] ]},
    { exhibit: 'Interface Fa0/7 connects to a printer. It is configured as PortFast and BPDU Guard. A small unmanaged switch is accidentally connected and sends BPDUs.', qs: [
      ['What is the expected result?', ['Fa0/7 goes err-disabled','Fa0/7 becomes root port','Fa0/7 becomes loop-inconsistent','Fa0/7 changes to trunk automatically'], 0, 'BPDU Guard disables the port when a BPDU arrives on a protected edge port.'],
      ['Which recovery action is typically needed after fixing the cabling?', ['Shutdown/no shutdown the interface or use errdisable recovery','Change the bridge MAC','Clear the ARP cache only','Reload the root bridge'], 0, 'BPDU Guard usually requires manual or configured errdisable recovery.'],
      ['Which command would help verify err-disabled interfaces?', ['show interfaces status err-disabled','show ip route','show cdp traffic','show vlan brief only'], 0, '`show interfaces status err-disabled` is commonly used to find ports disabled by protection features.'] ]},
    { exhibit: 'SW1 runs rapid-pvst. SW2 runs legacy pvst. They connect over a trunk carrying VLAN 10.', qs: [
      ['What is the safest high-level expectation?', ['They can interoperate, but SW1 may use legacy 802.1D behavior on that port/VLAN','The trunk cannot come up','SW2 automatically converts to Rapid PVST+ globally','All ports become PortFast'], 0, 'Rapid STP is backward-compatible and can fall back on a port talking to legacy STP.'],
      ['What is the troubleshooting impact?', ['Convergence may be slower on the legacy-facing port','OSPF will fail','Native VLAN must be 4096','ARP cannot work on VLAN 10'], 0, 'The RSTP advantage can be lost where it interoperates with legacy STP.'],
      ['Which command verifies the local STP mode?', ['show spanning-tree summary','show ip ospf neighbor','show controllers','show access-lists'], 0, '`show spanning-tree summary` displays the configured spanning tree mode.'] ]}
  ];
  topoScenarios.forEach(s => s.qs.forEach(item => addSingle('Topology analysis', item[0], item[1], item[2], item[3], s.exhibit)));

  const outputs = [
    { out: 'VLAN0010\n  Spanning tree enabled protocol rstp\n  Root ID    Priority    24586\n             Address     0011.1111.1111\n             Cost        4\n             Port        25 (GigabitEthernet0/1)\n  Bridge ID  Priority    32778\n             Address     0022.2222.2222\n\nInterface           Role Sts Cost Prio.Nbr Type\nGi0/1               Root FWD 4    128.25   P2p\nGi0/2               Desg FWD 4    128.26   P2p\nFa0/10              Desg FWD 19   128.10   Edge P2p', qs: [
      ['Is the local switch the root for VLAN 10?', ['Yes','No','Only for access ports','Cannot tell'], 1, 'Root ID and Bridge ID differ, and a root port is listed.'],
      ['Which interface is the root port?', ['Gi0/1','Gi0/2','Fa0/10','No root port'], 0, 'The role column shows Gi0/1 as Root FWD.'],
      ['What does `Edge P2p` on Fa0/10 imply?', ['It is treated as an edge/PortFast point-to-point port','It is a routed OSPF point-to-point port','It is blocked','It is the root port'], 0, 'Edge indicates PortFast/edge behavior.'] ]},
    { out: 'VLAN0020\n  Spanning tree enabled protocol rstp\n  Root ID    Priority    24596\n             Address     00aa.aaaa.aaaa\n             This bridge is the root\n  Bridge ID  Priority    24596\n             Address     00aa.aaaa.aaaa\n\nInterface           Role Sts Cost Prio.Nbr Type\nGi1/0/1             Desg FWD 4    128.1    P2p\nGi1/0/2             Desg FWD 4    128.2    P2p', qs: [
      ['Which statement is correct?', ['The local switch is root for VLAN 20','Gi1/0/1 is blocked','Root ID is learned from another switch','VLAN 20 is disabled'], 0, '`This bridge is the root` confirms it.'],
      ['What role should root bridge ports normally show?', ['Designated','Root','Alternate','Backup only'], 0, 'The root bridge has designated ports on normal segments.'],
      ['If another switch with priority 4096 joins VLAN 20, what likely changes?', ['The new switch may become root','This switch remains root because it was root first','STP shuts down','All links become trunks'], 0, 'A lower bridge ID can win root election.'] ]},
    { out: 'VLAN0030\n  Spanning tree enabled protocol ieee\nInterface           Role Sts Cost Prio.Nbr Type\nGi0/1               Root FWD 4    128.1    P2p\nGi0/2               Altn BLK 4    128.2    P2p', qs: [
      ['Which protocol behavior is shown?', ['Legacy IEEE 802.1D/PVST-style for that VLAN','Rapid PVST+ only','MST region mismatch only','STP disabled'], 0, 'The protocol field says ieee, not rstp.'],
      ['What is the status of Gi0/2?', ['Blocked alternate path','Forwarding root port','Forwarding designated port','Err-disabled'], 0, 'Altn BLK means alternate blocked.'],
      ['Which user traffic forwarding statement is true for Gi0/2?', ['It does not forward user frames while blocked','It forwards only ARP','It forwards only native VLAN frames','It forwards because alternate means backup-forwarding'], 0, 'Blocked/alternate ports do not forward user data frames.'] ]},
    { out: 'Switch# show spanning-tree summary\nSwitch is in rapid-pvst mode\nRoot bridge for: VLAN0010, VLAN0020\nExtended system ID is enabled\nPortfast Default is disabled\nPortFast BPDU Guard Default is enabled', qs: [
      ['Which VLANs is this switch root for?', ['10 and 20','All VLANs','Only VLAN 1','None'], 0, 'The summary explicitly lists VLAN0010 and VLAN0020.'],
      ['What is true about BPDU Guard default?', ['It applies to PortFast-enabled ports by default','It shuts every trunk immediately','It disables STP','It becomes root guard'], 0, 'The global PortFast BPDU Guard default affects PortFast ports.'],
      ['What still must be configured for a normal access port to benefit from this BPDU Guard default?', ['PortFast on that access port, or PortFast default','OSPF','A static default route','A VTP domain password'], 0, 'The global BPDU Guard default is tied to PortFast-enabled ports.'] ]},
    { out: '%SPANTREE-2-ROOTGUARD_BLOCK: Root guard blocking port GigabitEthernet1/0/24 on VLAN0010.', qs: [
      ['What caused this message?', ['A superior BPDU was received on a Root Guard port','A BPDU was received on a BPDU Guard edge port','BPDUs stopped arriving on an alternate port','The link changed speed'], 0, 'Root Guard blocks when superior BPDUs appear on a protected designated port.'],
      ['What is the port\'s effective forwarding behavior?', ['It is not forwarding user traffic for that VLAN','It forwards faster','It becomes PortFast','It becomes a router port'], 0, 'Root-inconsistent blocks traffic for the affected VLAN.'],
      ['How can it recover?', ['Stop receiving superior BPDUs','Clear the ARP cache','Configure an IP address','Change native VLAN only'], 0, 'Root Guard recovery is automatic when superior BPDUs stop.'] ]},
    { out: '%SPANTREE-2-LOOPGUARD_BLOCK: Loop guard blocking port GigabitEthernet1/0/3 on VLAN0020.', qs: [
      ['Which failure did the switch detect?', ['Expected BPDUs stopped arriving on a protected port','A superior BPDU arrived on an edge port','The port failed DHCP','The port negotiated half-duplex'], 0, 'Loop Guard reacts to missing BPDUs where BPDUs are expected.'],
      ['Which state name is associated with this?', ['Loop-inconsistent','Root-inconsistent','Err-disabled','Shutdown'], 0, 'Loop Guard places the port in loop-inconsistent state.'],
      ['What is the usual recovery behavior?', ['Automatic when BPDUs are received again','Never; reload required','Only after changing VLAN number','Only after deleting STP'], 0, 'Loop-inconsistent clears when valid BPDUs return.'] ]},
    { out: '%SPANTREE-2-BLOCK_BPDUGUARD: Received BPDU on port Fa0/12 with BPDU Guard enabled. Disabling port.\n%PM-4-ERR_DISABLE: bpduguard error detected on Fa0/12, putting Fa0/12 in err-disable state', qs: [
      ['Which protection feature triggered?', ['BPDU Guard','Root Guard','Loop Guard','BPDU Filter'], 0, 'The log says BPDU Guard and err-disable.'],
      ['Which situation most likely caused it?', ['A switch was connected to a protected PortFast/edge port','The root bridge failed','The native VLAN is 999','OSPF adjacency reset'], 0, 'BPDU Guard sees a BPDU on an edge/PortFast port.'],
      ['Which command helps find the disabled port status?', ['show interfaces status err-disabled','show ip route summary','show vlan internal usage','show clock detail'], 0, 'Err-disabled interfaces can be checked with `show interfaces status err-disabled`.'] ]},
    { out: 'VLAN0040\nInterface           Role Sts Cost Prio.Nbr Type\nPo1                 Root FWD 3    128.64   P2p\nGi1/0/1             Desg FWD 4    128.1    P2p\nGi1/0/2             Desg FWD 4    128.2    P2p', qs: [
      ['What does Po1 represent to STP?', ['A logical EtherChannel interface','A disabled VLAN','A PortFast host only','A router subinterface'], 0, 'Po1 is a port-channel and STP treats it as one logical port.'],
      ['Which interface is the root port?', ['Po1','Gi1/0/1','Gi1/0/2','All designated ports'], 0, 'Role Root FWD identifies the root port.'],
      ['Why might the cost be lower than a single Gigabit link?', ['EtherChannel logical bandwidth/cost calculation','It is blocked','BPDU Guard is enabled','It is VLAN 1 only'], 0, 'Port-channel cost can reflect aggregated bandwidth/platform calculation.'] ]},
    { out: 'VLAN0050\n  Spanning tree enabled protocol rstp\nInterface           Role Sts Cost Prio.Nbr Type\nGi0/1               Root FWD 4    128.1    P2p\nGi0/2               Desg FWD 4    128.2    P2p\nGi0/3               Altn BLK 4    128.3    P2p', qs: [
      ['Which port is the backup path toward the root if Gi0/1 fails?', ['Gi0/3','Gi0/2','All forwarding ports','None; RSTP has no backup'], 0, 'An alternate port is a backup path to the root.'],
      ['Which port is forwarding away from this switch for its segment?', ['Gi0/2','Gi0/3','No designated ports','Only Gi0/1'], 0, 'Desg FWD means designated forwarding.'],
      ['If Gi0/1 fails, what is likely under RSTP?', ['Gi0/3 can transition rapidly to forwarding if it becomes the best path','Gi0/3 must wait 50 minutes','Gi0/2 becomes administratively down','STP disables VLAN 50'], 0, 'RSTP alternate ports can provide rapid convergence.'] ]},
    { out: 'SW1# show spanning-tree vlan 60\nVLAN0060\n  Root ID    Priority    32828\n             Address     0001.0001.0001\n             Cost        19\n             Port        10 (FastEthernet0/10)\n  Bridge ID  Priority    32828\n             Address     0002.0002.0002', qs: [
      ['Why can Root ID priority and Bridge ID priority both show 32828 but different switches exist?', ['The priority includes VLAN 60, and MAC decides the lower bridge ID','The output is impossible','Priority is ignored when VLAN is above 50','The local switch is root'], 0, 'Both have default base priority plus VLAN ID. The lower MAC in Root ID wins.'],
      ['Which field shows the local switch is not root?', ['Root ID address differs from Bridge ID address','The VLAN is 60','The port is FastEthernet','Cost is 19'], 0, 'If local root, Root ID and Bridge ID would match and show `This bridge is the root`.'],
      ['Which interface is SW1 using toward the root?', ['Fa0/10','Cannot be determined','All interfaces','No root port'], 0, 'The Root ID section lists Port 10 (Fa0/10).'] ]}
  ];
  outputs.forEach(block => block.qs.forEach(item => addSingle('Analyze output', item[0], item[1], item[2], item[3], block.out)));

  const commands = [
    ['Enable Rapid PVST+ globally.', ['spanning-tree mode rapid-pvst'], 'Global config mode: choose the spanning-tree mode.', 'This is a global `spanning-tree mode ...` command.'],
    ['Configure this switch as the primary root for VLAN 10 using the Cisco macro.', ['spanning-tree vlan 10 root primary'], 'The root primary macro adjusts the priority to prefer this switch as root.', 'Use `root primary`.'],
    ['Configure this switch as the secondary root for VLANs 10 and 20 using the Cisco macro.', ['spanning-tree vlan 10,20 root secondary'], 'The best exact answer for VLAN 10 and 20 is `spanning-tree vlan 10,20 root secondary`.', 'Use comma-separated VLAN list.'],
    ['Set VLAN 30 bridge priority to 24576.', ['spanning-tree vlan 30 priority 24576'], 'Bridge priority is configured per VLAN.', 'Priority is a multiple of 4096.'],
    ['Enable PortFast on the current access interface.', ['spanning-tree portfast'], 'Interface-level PortFast moves an edge port rapidly to forwarding.', 'Interface config mode.'],
    ['Enable PortFast globally on all nontrunking access ports.', ['spanning-tree portfast default'], 'Global PortFast default applies to access ports, not trunks.', 'Global command includes `default`.'],
    ['Enable BPDU Guard on the current interface.', ['spanning-tree bpduguard enable'], 'Interface-level BPDU Guard protects the port by err-disabling on BPDU receipt.', 'Interface config mode; use `bpduguard enable`.'],
    ['Enable BPDU Guard globally for PortFast-enabled ports.', ['spanning-tree portfast bpduguard default'], 'This is the standard global command paired with PortFast edge ports.', 'The command starts with `spanning-tree portfast ...`.'],
    ['Enable Root Guard on the current interface using modern IOS syntax.', ['spanning-tree guard root'], 'Root Guard is interface-level and blocks superior BPDUs with root-inconsistent state.', 'Use `guard root`.'],
    ['Enable Loop Guard on the current interface.', ['spanning-tree guard loop'], 'Loop Guard is interface-level and protects against missing BPDUs.', 'Use `guard loop`.'],
    ['Enable Loop Guard globally.', ['spanning-tree loopguard default'], 'The global default applies Loop Guard behavior broadly where appropriate.', 'Global command includes `loopguard default`.'],
    ['Show the STP status for VLAN 10 only.', ['show spanning-tree vlan 10'], 'This filters the STP output to a specific VLAN instance.', 'Privileged EXEC show command.'],
    ['Show the STP summary including mode and root bridge VLANs.', ['show spanning-tree summary'], 'The summary is the fastest check for STP mode and root bridge list.', 'Use `summary`.'],
    ['Show detailed STP information for interface Gi0/1.', ['show spanning-tree interface gigabitethernet0/1 detail','show spanning-tree interface gi0/1 detail'], 'The detail form shows port state, timers, BPDU counts, and PortFast-related details.', 'Include `interface` and `detail`.'],
    ['Show all currently blocked STP ports.', ['show spanning-tree blockedports'], 'This command summarizes blocked STP ports.', 'One word: blockedports.'],
    ['Disable BPDU Guard on the current interface.', ['no spanning-tree bpduguard enable'], 'The `no` form removes interface-level BPDU Guard.', 'Use `no` before the exact feature command.'],
    ['Remove Root Guard/Loop Guard from the current interface.', ['spanning-tree guard none','no spanning-tree guard root','no spanning-tree guard loop'], 'Modern IOS supports `spanning-tree guard none` to remove guard behavior.', 'Set guard to `none`.'],
    ['Enable BPDU Filter on the current interface. Use with caution.', ['spanning-tree bpdufilter enable'], 'Per-interface BPDU Filter suppresses BPDUs and can be dangerous on switch links.', 'Interface config; feature is `bpdufilter`.'],
    ['Enable BPDU Filter globally for PortFast ports.', ['spanning-tree portfast bpdufilter default'], 'Global BPDU Filter is tied to PortFast default behavior.', 'Starts with `spanning-tree portfast`.'],
    ['Configure interface Gi0/2 as an edge trunk using PortFast trunk.', ['interface gigabitethernet0/2\nspanning-tree portfast trunk','interface gi0/2\nspanning-tree portfast trunk'], 'Edge trunks to routers/servers may use PortFast trunk when no L2 loop exists.', 'Two lines: enter interface, then PortFast trunk.'],
    ['Set the STP port cost of the current interface to 8 for VLAN 10.', ['spanning-tree vlan 10 cost 8'], 'Interface-level per-VLAN cost changes path selection.', 'Interface config; include VLAN and cost.'],
    ['Set the STP port priority of the current interface to 64 for VLAN 20.', ['spanning-tree vlan 20 port-priority 64'], 'Port priority can influence tie-breakers; lower is preferred.', 'Interface config; use `port-priority`.'],
    ['Display interfaces currently err-disabled due to protection features.', ['show interfaces status err-disabled'], 'This show command is useful after BPDU Guard events.', '`show interfaces status ...`.'],
    ['Recover a fixed err-disabled port Fa0/12 manually from interface config mode.', ['interface fastethernet0/12\nshutdown\nno shutdown','interface fa0/12\nshutdown\nno shutdown'], 'After fixing the cause, shutdown/no shutdown reinitializes the port.', 'Bounce the interface.'],
    ['Configure automatic errdisable recovery for BPDU Guard globally.', ['errdisable recovery cause bpduguard'], 'This allows automatic recovery after the recovery interval, if configured.', 'Global command starts with `errdisable recovery cause`.'],
    ['Set errdisable recovery interval to 300 seconds.', ['errdisable recovery interval 300'], 'This sets the recovery timer for enabled errdisable causes.', 'Global command; interval in seconds.'],
    ['Verify the current running STP-related configuration.', ['show running-config | include spanning-tree','show run | include spanning-tree'], 'Filtering the running-config quickly shows spanning-tree commands.', 'Use a pipe include filter.'],
    ['Show the STP information for the root bridge path and local bridge on all VLANs.', ['show spanning-tree'], 'The base command shows STP state per VLAN/instance.', 'No arguments needed.'],
    ['Configure VLANs 10-20 to use priority 28672.', ['spanning-tree vlan 10-20 priority 28672'], 'A VLAN range can be used with the priority command.', 'Use a VLAN range.'],
    ['Change the current interface to prefer it as the forwarding port by lowering its cost to 4 for VLAN 100.', ['spanning-tree vlan 100 cost 4'], 'Lower STP cost is preferred when selecting paths.', 'Interface config; lower cost wins.'],
    ['Globally disable PortFast default.', ['no spanning-tree portfast default'], 'The `no` form disables the global PortFast default behavior.', 'Global config; use `no`.'],
    ['Globally disable PortFast BPDU Guard default.', ['no spanning-tree portfast bpduguard default'], 'The `no` form removes global BPDU Guard default for PortFast ports.', 'Global config; same command with `no`.'],
    ['Configure Rapid PVST+ and make this switch root primary for VLAN 99. Provide the two commands.', ['spanning-tree mode rapid-pvst\nspanning-tree vlan 99 root primary'], 'Mode is global; root primary is per VLAN.', 'Two global commands.'],
    ['On interface Fa0/5, configure safe host-facing STP behavior: PortFast plus BPDU Guard. Provide commands from global config mode.', ['interface fastethernet0/5\nspanning-tree portfast\nspanning-tree bpduguard enable','interface fa0/5\nspanning-tree portfast\nspanning-tree bpduguard enable'], 'Host-facing access ports should typically use PortFast with BPDU Guard.', 'Enter the interface, then two spanning-tree commands.'],
    ['On interface Gi1/0/24 facing a downstream access switch, prevent it from becoming a root port because of superior BPDUs.', ['interface gigabitethernet1/0/24\nspanning-tree guard root','interface gi1/0/24\nspanning-tree guard root'], 'Root Guard belongs on designated ports where the root should never appear downstream.', 'Use Root Guard, not BPDU Guard, if the neighbor is a switch that may legitimately send BPDUs.'],
    ['On interface Gi1/0/2, protect against missing BPDUs on a redundant point-to-point link.', ['interface gigabitethernet1/0/2\nspanning-tree guard loop','interface gi1/0/2\nspanning-tree guard loop'], 'Loop Guard protects root/alternate links from unidirectional BPDU loss.', 'Use Loop Guard.'],
    ['Show whether interface Fa0/1 is configured as PortFast.', ['show spanning-tree interface fastethernet0/1 portfast','show spanning-tree interface fa0/1 portfast'], 'This command directly checks PortFast status on the interface.', 'End the command with `portfast`.'],
    ['Change classic PVST+ mode globally, not Rapid PVST+.', ['spanning-tree mode pvst'], 'PVST+ is the legacy per-VLAN STP mode.', 'Use `mode pvst`.']
  ];
  commands.forEach(c => addCommand('IOS command', c[0], c[1], c[2], c[3]));

  const guardQs = [
    ['A distribution switch port should always be designated toward the access layer. If the access switch sends a superior BPDU, the port should stop forwarding but recover automatically when the superior BPDU disappears. Which feature?', ['Root Guard','BPDU Guard','Loop Guard','BPDU Filter'], 0, 'Root Guard puts the port into root-inconsistent while superior BPDUs are received.'],
    ['A printer port is configured with PortFast. The requirement is to shut the port if any BPDU is received. Which feature?', ['BPDU Guard','Root Guard','Loop Guard','Root secondary'], 0, 'BPDU Guard is the correct host-edge protection.'],
    ['An alternate port should not become forwarding just because it stopped hearing BPDUs. Which feature?', ['Loop Guard','BPDU Guard','BPDU Filter','PortFast'], 0, 'Loop Guard keeps it loop-inconsistent until BPDUs return.'],
    ['Why are Root Guard and Loop Guard conceptually applied to different port intentions?', ['Root Guard protects designated ports from becoming root ports; Loop Guard protects root/alternate ports from missing BPDUs','Both only work on PortFast ports','Both disable STP completely','Both require routed ports'], 0, 'Root Guard and Loop Guard protect different failure modes and port roles.'],
    ['Which feature can create the most silent failure if enabled per-interface on an inter-switch trunk?', ['BPDU Filter','BPDU Guard','Root Guard','Loop Guard'], 0, 'Per-interface BPDU Filter can suppress STP communication completely on that link.'],
    ['A Root Guard port is root-inconsistent. Which condition clears it?', ['The port stops receiving superior BPDUs','The switch receives more superior BPDUs','The VLAN is renamed','The MAC table is cleared'], 0, 'Root-inconsistent clears automatically when superior BPDUs stop.'],
    ['A Loop Guard port is loop-inconsistent. Which condition clears it?', ['The port receives valid BPDUs again','The port receives no BPDUs for max-age','The switch priority increases','The native VLAN changes'], 0, 'Loop-inconsistent clears when BPDUs return.'],
    ['A BPDU Guard port is err-disabled. Which statement is most accurate?', ['It usually requires manual or configured errdisable recovery after fixing the cause','It automatically forwards as soon as superior BPDUs stop','It becomes root-inconsistent','It keeps forwarding but logs warnings'], 0, 'BPDU Guard err-disables the port; recovery is separate.'],
    ['Where should PortFast normally be enabled?', ['End-host/access edge ports','Redundant switch-to-switch trunks','Core-to-distribution trunks','All ports including uplinks'], 0, 'PortFast is for edge ports where no Layer 2 loop should form.'],
    ['Which pair is the standard safe baseline for user-facing access ports?', ['PortFast + BPDU Guard','Root Guard + BPDU Filter','Loop Guard + BPDU Filter','Disable STP + PortFast'], 0, 'PortFast improves host startup; BPDU Guard protects against accidental switch connection.'],
    ['A switch should be preferred as root only if the intended root fails, while still beating all default-priority switches. Which macro?', ['root secondary','root primary','guard root','portfast default'], 0, 'Root secondary positions the switch as backup root against default-priority switches.'],
    ['What does Root Guard protect against better than BPDU Guard on a downstream switch link?', ['Unexpected root takeover while still allowing normal BPDU participation','Loss of DHCP leases','Native VLAN tagging','Dynamic trunking'], 0, 'Root Guard allows BPDUs but blocks superior ones from changing root placement.'],
    ['What does BPDU Guard protect against better than Root Guard on a host port?', ['An accidental switch connection to an edge port','A unidirectional fiber causing missed BPDUs','A root bridge priority tie','An STP cost tie'], 0, 'BPDU Guard shuts the port when any BPDU appears on an edge port.'],
    ['What is the most precise reason not to solve every STP risk with BPDU Filter?', ['It can hide topology information from STP and allow loops','It makes every switch root','It prevents MAC learning','It only works on routers'], 0, 'Filtering BPDUs can remove STP ability to detect loops.'],
    ['In a CCNA troubleshooting question, `root-inconsistent` points to which feature first?', ['Root Guard','Loop Guard','BPDU Guard','PortFast'], 0, 'Root-inconsistent is Root Guard behavior.']
  ];
  guardQs.forEach(g => addSingle('Guard scenario', g[0], g[1], g[2], g[3]));

  const matches = [
    ['Match the STP/RSTP role to the best description.', ['Root port','Designated port','Alternate port','Backup port'], ['Best path from non-root switch toward root','Forwarding port elected for a segment','Discarding backup path to root','Redundant local port on same segment'], {'Root port':'Best path from non-root switch toward root','Designated port':'Forwarding port elected for a segment','Alternate port':'Discarding backup path to root','Backup port':'Redundant local port on same segment'}, 'These are the core STP/RSTP port-role meanings.'],
    ['Match the protection feature to the trigger.', ['BPDU Guard','Root Guard','Loop Guard','BPDU Filter'], ['Receives any BPDU on protected edge port','Receives superior BPDU on protected designated port','Stops receiving expected BPDUs','Suppresses sending/receiving BPDUs'], {'BPDU Guard':'Receives any BPDU on protected edge port','Root Guard':'Receives superior BPDU on protected designated port','Loop Guard':'Stops receiving expected BPDUs','BPDU Filter':'Suppresses sending/receiving BPDUs'}, 'Each protection feature has a specific failure model.'],
    ['Match the state to frame/MAC behavior in classic STP.', ['Blocking','Listening','Learning','Forwarding'], ['Receives BPDUs, no MAC learning, no user forwarding','Receives BPDUs, prepares but no MAC learning','Learns MACs, no user forwarding','Learns MACs and forwards user frames'], {'Blocking':'Receives BPDUs, no MAC learning, no user forwarding','Listening':'Receives BPDUs, prepares but no MAC learning','Learning':'Learns MACs, no user forwarding','Forwarding':'Learns MACs and forwards user frames'}, 'Classic 802.1D uses blocking/listening/learning/forwarding.'],
    ['Match the Cisco command to the goal.', ['spanning-tree mode rapid-pvst','spanning-tree vlan 10 root primary','spanning-tree portfast','spanning-tree guard root'], ['Enable Rapid PVST+ globally','Influence VLAN 10 root election','Make current edge port skip listening/learning','Prevent superior BPDUs from changing root via this port'], {'spanning-tree mode rapid-pvst':'Enable Rapid PVST+ globally','spanning-tree vlan 10 root primary':'Influence VLAN 10 root election','spanning-tree portfast':'Make current edge port skip listening/learning','spanning-tree guard root':'Prevent superior BPDUs from changing root via this port'}, 'Know command intent, not just syntax.'],
    ['Match the show-output term to meaning.', ['Root ID','Bridge ID','Altn BLK','This bridge is the root'], ['Elected root bridge for the instance','Local switch bridge ID','Alternate blocked port','Local switch won root election'], {'Root ID':'Elected root bridge for the instance','Bridge ID':'Local switch bridge ID','Altn BLK':'Alternate blocked port','This bridge is the root':'Local switch won root election'}, 'These are high-frequency output clues.'],
    ['Match the path cost to classic short-cost speed.', ['10 Mbps','100 Mbps','1 Gbps','10 Gbps'], ['100','19','4','2'], {'10 Mbps':'100','100 Mbps':'19','1 Gbps':'4','10 Gbps':'2'}, 'Short path cost method uses 100/19/4/2 for these common speeds.'],
    ['Order the root port tie-breaker logic by matching step to criterion.', ['1','2','3','4'], ['Lowest root path cost','Lowest sender bridge ID','Lowest sender port ID','Lowest local port ID'], {'1':'Lowest root path cost','2':'Lowest sender bridge ID','3':'Lowest sender port ID','4':'Lowest local port ID'}, 'This exact order matters in hard topology questions.'],
    ['Match feature to the best deployment location.', ['PortFast','BPDU Guard','Root Guard','Loop Guard'], ['Host-facing edge ports','Host-facing edge ports where BPDUs should never appear','Designated ports toward places root must not appear','Root/alternate redundant links expecting BPDUs'], {'PortFast':'Host-facing edge ports','BPDU Guard':'Host-facing edge ports where BPDUs should never appear','Root Guard':'Designated ports toward places root must not appear','Loop Guard':'Root/alternate redundant links expecting BPDUs'}, 'Feature placement is often what separates easy from real CCNA questions.'],
    ['Match Rapid STP concept to description.', ['Discarding','Proposal/agreement','Edge port','Alternate port'], ['Non-forwarding RSTP state','Rapid transition mechanism on point-to-point links','Port toward end host','Backup path to root'], {'Discarding':'Non-forwarding RSTP state','Proposal/agreement':'Rapid transition mechanism on point-to-point links','Edge port':'Port toward end host','Alternate port':'Backup path to root'}, 'Rapid STP has its own state/transition vocabulary.'],
    ['Match the inconsistency/disabled state to the feature.', ['Err-disabled','Root-inconsistent','Loop-inconsistent','Normal alternate blocking'], ['BPDU Guard','Root Guard','Loop Guard','STP loop prevention without a guard feature'], {'Err-disabled':'BPDU Guard','Root-inconsistent':'Root Guard','Loop-inconsistent':'Loop Guard','Normal alternate blocking':'STP loop prevention without a guard feature'}, 'The state name usually reveals the feature involved.'],
    ['Match the per-VLAN design choice to the result.', ['SW1 root VLAN 10, SW2 root VLAN 20','SW1 root all VLANs','Default priorities everywhere','Disable STP on a redundant VLAN'], ['Possible load sharing','Single primary L2 path for all VLANs','Lowest MAC may accidentally become root','Loop risk'], {'SW1 root VLAN 10, SW2 root VLAN 20':'Possible load sharing','SW1 root all VLANs':'Single primary L2 path for all VLANs','Default priorities everywhere':'Lowest MAC may accidentally become root','Disable STP on a redundant VLAN':'Loop risk'}, 'Root placement should be intentional.'],
    ['Match command to the show/troubleshooting purpose.', ['show spanning-tree vlan 10','show spanning-tree blockedports','show spanning-tree summary','show interfaces status err-disabled'], ['Inspect one VLAN instance','List STP-blocked ports','Check mode/root summary','Find ports disabled by protection'], {'show spanning-tree vlan 10':'Inspect one VLAN instance','show spanning-tree blockedports':'List STP-blocked ports','show spanning-tree summary':'Check mode/root summary','show interfaces status err-disabled':'Find ports disabled by protection'}, 'Command selection is a major practical skill.']
  ];
  matches.forEach(m => addMatch('Drag/drop', m[0], m[1], m[2], m[3], m[4]));

  addMulti('Multi-select', 'Which two statements about Rapid PVST+ are correct?', ['It creates one RSTP instance per VLAN','It eliminates all STP blocking','It uses RSTP concepts such as alternate ports and discarding state','It requires EtherChannel on every trunk'], [0,2], 'Rapid PVST+ is Cisco per-VLAN RSTP. It still blocks redundant paths when needed.');

  return q.slice(0, 200);
}
